### ISSUE TITLE
Constant problems with the mod

### ISSUE THREAD

**Issue by Aabaddon** [Zanckor/QuestAPI#18]
[2023-08-29-2.log.gz](https://github.com/Zanckor/QuestAPI/files/12471007/2023-08-29-2.log.gz)
(i had to upload the zip because the log was too heavy it seems)

some times when opening the game it says it cant find the config file or something (i lost that log im sorry, but happened a couple times) then every time with this mod installed it spams in the logs "Your identifier minimalist_questapi is incorrect or you have no screen registered"

this mod also causes massive lag in my game for some reason, im no programer so ill leave this here so you can check it, sorry for the trouble

(its the lastest version of the mod in the lastest forge 1.20.1)

**Comment by Zanckor** [comment]
Hello Aabaddon! This bug is a known bug, but fixed in latest version, so I would need more information about this.
Also want to know how this lag is being caused.

To a proper conversation, I recommend you to join QuestAPI's discord so I can ask you for more files 😊
https://discord.gg/pBUACptquc

*Edit: Seems that "Your identifier..." bug is still there, I'm gonna fix that right now, anyway you should join so we can talk about that lag

**Comment by Aabaddon** [comment]
sure thing, thanks dude!
